{
 "title": "ETH staking dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_job", "query": "beacon node" },
   { "name": "validator_job", "query": "validator" }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "text",
   "description": "To delete this panel: left click on the title, then chose remove",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "content": "\n## Presentation\n-----\nWelcome to my dashboard!\n\nEnsure to update your grafana to the version 7.0.1 or more. Previous version won't have everything working properly.\n\nIf you face any issue to understand a panel or to know what to do, make sure to read the small note on the corner top left of the panel if there is one!\n\n\n## Earning panels exceptions\n-----\nThe earning panels are supposing that you have done deposits of 32 ETH exactly. If you see some incoherence in this values it's probably because you have deposited more than 32 ETH.\nIf so, you can fix the total earning panel by adding at the end of the query the substraction of your excedend 32 ETH. For the others earning panels (hourly daily weekly monthly),\nit will be fixed by itself with time, but you can still fix it temporarily by doing the same job than on the total earning panel (then don't forget to remove your temporarily fix once it has been fixed automatically)\n\n##### Total earning fix\n-----\nIf you sent 32.5 ETH on each validator and you have 5 validators, the total earning query will look like\n```\nsum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32 - 0.5*5\n```\n\nTo edit a panel, left click on the panel title then chose edit, then ensure to save the dashboard !\n\n\n\n### Bug!\n-----\nIf you find a bug, please report it to me on discord, Ocaa/grums. I'm foundable on the prysm discord then dm me directly. I'll try to give a fix and update the dashboard !\nThanks for all the reports\n\n\n\n\n-----\nAfter reading it, you can now delete me. And don't forget to save the dashboard after deleting me! (button on the upper right) :)\n\nEnjoy\n\n\n\n"
  },
  {
   "title": "VALIDATOR",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly earning",
   "type": "stat",
   "description": "This panel shows the number of ETH earned during the last hour, and the annualized % of the hourly earning.\n\nThose data won't be shown until the first validator is at least one hour old, or that you started prometheus at least one hour ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)/(avg_over_time(count(validator_balance > 16)[1h:30s])*32/24/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Daily earning",
   "type": "stat",
   "description": "This panel shows the number of ETH earned during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)/(avg_over_time(count(validator_balance > 16)[1d:12m])*32/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Weekly earning",
   "type": "stat",
   "description": "This panel shows the number of ETH earned during the last week, and the annualized % of the weekly earning.\n\nThose data won't be shown until the first validator is at least one week old, or that you started prometheus at least one week ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1w) - count(validator_balance > 16)*32 + count(validator_balance offset 1w > 0)*32)",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1w) - count(validator_balance > 16)*32 + count(validator_balance offset 1w > 0)*32)/(avg_over_time(count(validator_balance > 16)[1w:84m])*32*7/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Monthly earning",
   "type": "stat",
   "description": "This panel shows the number of ETH earned during the last month, and the annualized % of the monthly earning.\n\nThose data won't be shown until the first validator is at least one month old, or that you started prometheus at least one month ago. Ensure to run Prometheus with the flag `--storage.tsdb.retention.time=31d` if you want this panel to get enough data\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)/(avg_over_time(count(validator_balance > 16)[30d:6h])*32/12)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32",
     "legendFormat": "Earning (ETH)"
    },
    {
     "expr": "(sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32)*100/(count(validator_balance > 16 and validator_statuses == 3)*32)",
     "legendFormat": "ROI (%)"
    }
   ]
  },
  {
   "title": "Validator process started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$validator_job\"})/3600"
    }
   ]
  },
  {
   "title": "Total balance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    { "expr": "sum(validator_balance > 16)", "legendFormat": "Total balance" }
   ]
  },
  {
   "title": "Validator balance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_balance > 16, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Validator main info",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_statuses), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Validator vote summary",
   "type": "table-old",
   "description": "This panel will count only the votes done since your validator process started",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_failed_attestations)  , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_successful_aggregations)    , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_aggregations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_successful_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "BOTH",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "NODE",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 11, "x": 8, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "ALERTS",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hardware usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes", "label": "mem usage" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "memory {{job}}" },
    {
     "expr": "(process_cpu_seconds_total - process_cpu_seconds_total offset 15s) > 0*100/15/go_maxprocs",
     "legendFormat": "CPU {{job}}"
    }
   ]
  },
  {
   "title": "Balance validators status and participation rate",
   "type": "graph",
   "description": "This graph is made for trading purpose mostly.\nSupposing that if a lot of validators are exiting, price is gonna dump.\n\nAlso this can prevent to exit while exiting queue is too long, same for depositing while pending queue is too long.\n\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\"} / 10e8",
     "legendFormat": "Active"
    },
    {
     "expr": "validators_total_balance{state=\"Pending\"} / 10e8",
     "legendFormat": "Pending"
    },
    {
     "expr": "validators_total_balance{state=\"Exiting\"} / 10e8",
     "legendFormat": "Exiting"
    },
    {
     "expr": "total_voted_target_balances/total_eligible_balances*100",
     "legendFormat": "Participation rate"
    }
   ]
  },
  {
   "title": "Node process started",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$node_job\"})/3600"
    }
   ]
  },
  { "title": "All alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 35 } },
  {
   "title": "Slots behind",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "Slots behind"
    }
   ]
  },
  {
   "title": "Peers connected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Hourly log type counter",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"error\"}[1h]) > 0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "Warn: The process just restarted",
   "type": "graph",
   "description": "This alert is useful only for people who has automatic restart of the process after crash. \nThis can be made for example by using the prysm.bat file on windows with \"set PRYSM_AUTORESTART=true&\", or with docker with \"--restart always\"",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds)/3600",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "Alert: 50 slots behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"beacon node\"}",
     "legendFormat": "beacon node"
    },
    {
     "expr": "up{job=\"validator\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32",
     "legendFormat": "validators earning on 1h"
    }
   ]
  },
  {
   "title": "Alert: 50 errors  or 100 warns  in 1h",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"error\"}[1h]) > 0) ",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Alert: Validator has been slashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_statuses, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Alert: Participation rate < 66%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "total_voted_target_balances/total_eligible_balances*100"
    }
   ]
  }
 ]
}